baseURL: "https://camilonietom.com/" 
title: Cnm
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1 
        - name: Work in Progress
          url: inprogress/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
    

params:
    description: "Camilo Nieto-Matiz - Assistant Professor in Political Science, UT San Antonio"
    author: "Camilo Nieto-Matiz"
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pc
          subtitle: "I'm an Assistant Professor in the Department of Political Science at the University of Texas at San Antonio, where I also serve as Assistant Director for The UTSA Center for Public Opinion Research. I am also a Research Affiliate at the Violence and Transitional Justice Lab at Notre Dame's Kellogg Institute.

My research explores political violence, state building, criminal governance, and transitional justice, with a regional focus on Latin America. I investigate why some societies experience major outbreaks of violence, how state institutions and criminal groups operate during periods of conflict, and the mechanisms through which societies address human rights violations and rebuild governance after war"."
          
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:igelfeld@regensburg.edu
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
